name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      types: ${{ steps.changes.outputs.types }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15

      - name: Changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'packages/backend/**'
            frontend:
              - 'packages/frontend/**'
            types:
              - 'packages/types/**'

  types-build:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{needs.changes.outputs.types == 'true' || needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          save-always: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: cd packages/types && yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: types-build
          path: packages/types/dist/

  backend-build:
    needs: [changes, types-build]
    runs-on: ubuntu-latest
    if: ${{needs.changes.outputs.backend == 'true' || needs.changes.outputs.types == 'true'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          save-always: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Download types artifact
        uses: actions/download-artifact@v4
        with:
          name: types-build
          path: packages/types/dist

      - name: Build project
        run: cd packages/backend && yarn build

      - name: Builded
        run: echo "Backend Builded"

  backend-deploy:
    needs: backend-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for backend
        run: |
          docker build -t ${{  vars.DOCKER_HUB_USERNAME }}/backend -f docker/backend/start.Dockerfile .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login registry-1.docker.io -u "${{  vars.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image for backend
        run: docker push ${{  vars.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
                "imageUrl": "${{  vars.DOCKER_HUB_USERNAME }}/backend:latest"
              }' \
          https://api.render.com/v1/services/${{  vars.RENDER_SERVICE_ID }}/deploys

  frontend-build:
    needs: [changes, types-build]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.types == 'true'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          save-always: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Remove original types
        run: rm -rf packages/types/src

      - name: Download types artifact
        uses: actions/download-artifact@v4
        with:
          name: types-build
          path: packages/types/dist

      - name: Test frontend
        run: cd packages/frontend && yarn test

      - name: Build project
        run: cd packages/frontend && yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: packages/frontend/dist/

  frontend-deploy:
    needs: frontend-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: packages/frontend/dist/

      - name: Deploy to Vercel
        run: |
          yarn global add vercel
          vercel link --cwd packages/frontend/dist --yes --project flashcards-frontend --token ${{ secrets.VERCEL_TOKEN }}
          vercel --cwd packages/frontend/dist --yes --prod --token ${{ secrets.VERCEL_TOKEN }}
