name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 24.x

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Changed files
        id: changes
        uses: dorny/paths-filter@v4
        with:
          base: 'master'
          filters: |
            backend:
              - 'packages/backend/**'
            frontend:
              - 'packages/frontend/**'



  backend-build:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{needs.changes.outputs.backend == 'true'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Restore dependencies cache
        id: backend-dependencies-cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Save dependencies cache
        if: ${{ always() && steps.backend-dependencies-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ steps.backend-dependencies-cache.outputs.cache-primary-key }}

      - name: Build project
        run: cd packages/backend && yarn build

      - name: Builded
        run: echo "Backend Builded"

  backend-deploy:
    needs: backend-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend/start.Dockerfile
          push: true
          tags: ${{  vars.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
                "clearCache": "clear",
                "imageUrl": "docker.io/${{  vars.DOCKER_HUB_USERNAME }}/backend:latest"
              }' \
          https://api.render.com/v1/services/${{  vars.RENDER_SERVICE_ID }}/deploys

  frontend-build:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Restore dependencies cache
        id: frontend-dependencies-cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Save dependencies cache
        if: ${{ always() && steps.frontend-dependencies-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ steps.frontend-dependencies-cache.outputs.cache-primary-key }}

      #- name: Test frontend
      #  run: cd packages/frontend && yarn test

      
      - name: Build project
        run: cd packages/frontend && yarn build

      - name: Create vercel.json
        run: |
          cd packages/frontend/dist
          cat > vercel.json << 'EOF'
          {
            "rewrites": [
              {
                "source": "/api/:path*",
                "destination": "${{vars.BACKEND_URL}}/:path*"
              }
            ]
          }
          EOF

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: packages/frontend/dist/

  frontend-deploy:
    needs: frontend-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: packages/frontend/dist/

      - name: Deploy to Vercel
        run: |
          npx vercel@latest link --cwd packages/frontend/dist --yes --project flashcards-frontend --token ${{ secrets.VERCEL_TOKEN }}
          npx vercel@latest --cwd packages/frontend/dist --yes --prod --token ${{ secrets.VERCEL_TOKEN }}
